services:

  springboot:
    build: .
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    expose:
      - "8080"
      - "8000"
    networks:
      - net
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    depends_on:
      - springboot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge